SampleProject/Controllers/EncryptionController.cs
using Azure.Core.Pipeline;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Primitives;
using SampleProject.DAL;
using SampleProject.Models;
using System.Reflection.Metadata.Ecma335;
using System.Text;

namespace SampleProject.Controllers
{
    public class EncryptionController : Controller
    {

        public IActionResult Index()
        {
            return View(new EncryptionModel());
        }

        public IActionResult Encrypt(EncryptionModel model)
        {
            if (string.IsNullOrWhiteSpace(model.TextToEncrypt))
            {
                TempData["EmptyTextToEncrypt"] = "Empty text for encryption";
                return View("Index", model);
            }

            string output = TripleDesService.Encrypt(model.TextToEncrypt, model.Key);

            model.EncryptedText = output;
            model.Key = string.Empty;
            return View("Index", model);

        }

        public IActionResult Decrypt(EncryptionModel model)
        {
            if (string.IsNullOrEmpty(model.EncryptedText))
            {
                TempData["EmptyEncryptedText"] = "Empty text to decrypt";
                return View("Index", model);
            }
            var output = TripleDesService.Decrypt(model.EncryptedText, model.Key);

            model.DecryptedText = output;

            return View("Index", model);
        }

        public IActionResult DesEncryptDecryptIndex()
        {
            return View("DesEncryptDecryptIndex", new EncryptionModel());
        }


        public IActionResult DesEncryption(EncryptionModel model)
        {
            if (string.IsNullOrWhiteSpace(model.TextToEncrypt))
            {
                TempData["EmptyToEncrypt"] = "Empty text for Encryption";
                return View("DesEncryptDecryptIndex", model);
            }

            var output = DESService.Encrypt(model.TextToEncrypt, model.Key, model.Key2, model.Key3);
            model.EncryptedText = output.finalText;
            model.encryptionResult.encrypted1 = output.Text1;
            model.encryptionResult.decrypted1 = output.Text2;
            model.encryptionResult.finaltext = output.finalText;

            return View("DesEncryptDecryptIndex", model);

        }


        public IActionResult DesDecryption(EncryptionModel model)
        {

            Console.WriteLine(model.TextToEncrypt);


            model.encryptionResult.finaltext = model.EncryptedText;
            if (string.IsNullOrEmpty(model.encryptionResult.finaltext))
            {
                TempData["EmptyEncryptedText"] = "Empty text to decrypt";
                return View("DesEncryptDecryptIndex", model);
            }

            var output = DESService.Decrypt(model.encryptionResult.finaltext, model.Key, model.Key2, model.Key3);
            //model.DecryptedText = output;
            model.decryptionResult.decrypted1 = output.text1;
            model.decryptionResult.encrypted1 = output.text2;
            model.decryptionResult.finaltext = output.finaltext;



            return View("DesEncryptDecryptIndex", model);

        }


        string encryptedText = "";
        public IActionResult RSAEncryptDecryptIndex()
        {
            return View("RSAEncryptDecryptIndex", new RSAModel());


        }


        [HttpPost]
        public IActionResult RsaEncrypt(RSAModel model, string client, string privateKey, string publicKey)
        {
            if (!string.IsNullOrWhiteSpace(model.RSAencryption.Text) && !string.IsNullOrWhiteSpace(model.RSAencryption.UserInputKey))
            {

                var output = Convert.ToHexString(RSAService.EncryptMessage(model.RSAencryption.Text, model.RSAencryption.UserInputKey));


                Console.WriteLine(output);

                Console.WriteLine(" ");

                model.RSAencryption.HexString = output;
                model.RSAencryption.PublicKey = publicKey;
                model.RSAencryption.PrivateKey = privateKey;
                model.publicKeygeneration = string.Empty;
                model.privateKeygeneration = string.Empty;



                return View("RSAencryptdecryptIndex", model);
                //if (client == "client1")
                //{
                //    System.IO.File.WriteAllText(@"C:\Users\adark\source\repos\SampleProject\client2\EncryptedText.txt", output);
                //}
                //else if(client =="client2")
                //{
                //    System.IO.File.WriteAllText(@"C:\Users\adark\source\repos\SampleProject\client1\EncryptedText.txt", output);
                //}
                //TempData["success"] = "Successfully encrypted";
                //return View("RSAStatus", true);


            }
            return View("RSAStatus", false);
        }

        [HttpPost]
        public IActionResult RsaDecrypt(RSAModel model, string client, string originalText, string privateKey, string publicKey)
        {
            string output = string.Empty;

            string ReadTextFromFile = string.Empty;
            string ReadkeyFromFile = string.Empty;
            if (!string.IsNullOrEmpty(model.RSAencryption?.HexString))

            {
                //if (client == "client2")
                //{
                //    ReadTextFromFile = System.IO.File.ReadAllText(@"C:\Users\adark\source\repos\SampleProject\client2\EncryptedText.txt");
                //    ReadkeyFromFile = System.IO.File.ReadAllText(@"C:\Users\adark\source\repos\SampleProject\client2\MyPrivateKey.xml");
                //}
                //else if (client == "client1")
                //{

                //    ReadTextFromFile = System.IO.File.ReadAllText(@"C:\Users\adark\source\repos\SampleProject\client1\EncryptedText.txt");
                //    ReadkeyFromFile = System.IO.File.ReadAllText(@"C:\Users\adark\source\repos\SampleProject\client1\MyPrivateKey.xml");
                //}
                model.RSAencryption.HexString = model.RSAencryption.HexString.Trim();
                if (model.RSAencryption?.HexString.Length % 2 != 0)
                {
                    model.RSAencryption.HexString = "0" + model.RSAencryption.HexString;  // Make it even-length
                }
                output = RSAService.DecryptMessage(Convert.FromHexString(model.RSAencryption?.HexString), privateKey);
            }
            model.RSAdecryption.EncryptedText = model.RSAencryption.HexString;
            model.RSAdecryption.DecryptedText = output;

            //encryption model
            // model.RSAencryption.HexString = string.Empty;
            model.RSAencryption.Text = originalText;
            if (string.IsNullOrEmpty(model.RSAencryption.PublicKey))
            {
                model.RSAencryption.PublicKey = publicKey;
            }
            model.RSAencryption.PrivateKey = privateKey;
            model.client = client;
            //model.Signature = message;
            model.DisplaySignature = false;
            model.DisplayDecryptedTextInTextBox = true;
            return View("RSAencryptdecryptIndex", model);
        }


        [HttpPost]
        public IActionResult HashText(RSAModel model, string publicKey, string privateKey)
        {
            if (!string.IsNullOrEmpty(model.RSAdecryption.DecryptedText))
            {
                var hashOutput = RSAService.HashMessage(model.RSAdecryption.DecryptedText);
                model.HashOutput = Convert.ToHexString(hashOutput);

                if (string.IsNullOrEmpty(model.RSAencryption.PrivateKey))
                {
                    model.RSAencryption.PrivateKey = privateKey;
                }
                if (string.IsNullOrEmpty(model.RSAencryption.PublicKey))
                {
                    model.RSAencryption.PublicKey = publicKey;
                }
                model.DisplaySignature = false;
               // model.Signature = message;

                model.RSAdecryption.EncryptedText = model.RSAencryption.HexString;
                model.RSAencryption.HexString = string.Empty;




                return View("RSAencryptdecryptIndex", model);
            }
            return View("RSAStatus", false);
        }
        public IActionResult RSAdecryption(string cipherText)
        {

            //var output = RSAService.DecryptMessage(cipherText);
            //Console.WriteLine(output.plaintext);
            //Console.WriteLine("");
            //Console.WriteLine("PrivateKey :" + output.privateKey);

            //return Ok(output.plaintext + "\n\n\n" + "Private Key : " + output.privateKey);

            return Ok();

        }

        public IActionResult SubmitPublicKey()
        {
            return View("SubmitKeys", new SubmitKeyModel());
        }
        public IActionResult SubmitPublicKeyFromClient1()
        {
            return View("SubmitKeysToClient2", new SubmitKeyModel());
        }

        [HttpPost]
        public IActionResult SubmitPublicKeyForClient1(SubmitKeyModel model)
        {

            var output = RSAService.GenerateKeysforClient2();

            try
            {
                //EmailService.SendPublicKeyViaEmail(model.OriginEmail, model.EmailPassword, model.SourceEmail, output.publicKey);

                System.IO.File.WriteAllText(@"C:\Users\adark\source\repos\SampleProject\client1\Client2_PublicKey.xml", output.publicKey);
                System.IO.File.WriteAllText(@"C:\Users\adark\source\repos\SampleProject\client2\MyPrivateKey.xml", output.privateKey);
                Console.WriteLine("Done submit public keys");

            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception :" + ex.Message);
                return BadRequest("Exception :" + ex.Message);
            }


            TempData["SubmitPublicKeyFromClientsuccess"] = "Succesfully submitted";
            return View("RSAencryptdecryptIndex", new RSAModel());
        }

        [HttpPost]

SampleProject/Views/Encryption/DesEncryptDecryptIndex.cshtml
@model EncryptionModel

@{
    ViewBag.Title = "DES Encryption Example";
}

<h2> DES Encryption</h2>


@if (!string.IsNullOrEmpty(Model.Key) && TempData["EmptyTextToEncrypt"] != null)
{
    <div class="alert alert-danger">
        @TempData["EmptyTextToEncrypt"]
    </div>
}

@if (!string.IsNullOrEmpty(Model.Key) && TempData["EmptyEncryptedText"] != null)
{
    <div class="alert alert-danger">
        @TempData["EmptyEncryptedText"]
    </div>
}


@using (Html.BeginForm("DesEncryption", "Encryption", FormMethod.Post))
{
    <div>

        <label>Text to Encrypt:</label>
        @Html.TextBoxFor(m => m.TextToEncrypt)
    </div>
    <div>
        <label>Key (8 characters):</label>
        @Html.TextBoxFor(m => m.Key)
    </div>
    <div>
        <label>Key (8 characters):</label>
        @Html.TextBoxFor(m => m.Key2)
    </div>
    <div>
        <label>Key (8 characters):</label>
        @Html.TextBoxFor(m => m.Key3)
    </div>
    <div>
        <br />
        <input class="btn btn-primary" type="submit" value="Encrypt" />
    </div>
    <br />
}

@* @if (!string.IsNullOrEmpty(Model.EncryptedText))
{
    <div>
        <h4>Encrypted Text:</h4>
        <p>@Model.EncryptedText</p>
    </div>
} *@

@using (Html.BeginForm("DesDecryption", "Encryption", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(m => m.TextToEncrypt)
    </div>
    <div>
        @Html.HiddenFor(m => m.encryptionResult.encrypted1)
    </div>
    <div>
        <label>Encrypted Text:</label>
        @Html.TextBoxFor(m => m.EncryptedText)
    </div>
    <div>
        <label>Key (8 characters):</label>
        @Html.TextBoxFor(m => m.Key)
    </div>
    <div>
        <label>Key (8 characters):</label>
        @Html.TextBoxFor(m => m.Key2)
    </div>
    <div>
        <label>Key (8 characters):</label>
        @Html.TextBoxFor(m => m.Key3)
    </div>
    <div>
        <br />
        <input class="btn btn-primary" type="submit" value="Decrypt" />
    </div>
}


@if(!string.IsNullOrEmpty(Model.encryptionResult.encrypted1)
&& !string.IsNullOrEmpty(Model.encryptionResult.decrypted1) && 
!string.IsNullOrEmpty(Model.encryptionResult.finaltext))
{
       
    <br/> 
    <h5> Encryptions(EDE) Results </h5>
    <div> 
        <h7> Original Text : @Model.TextToEncrypt </h7> <br />
        <h7> CipherText 1 : @Model.encryptionResult.encrypted1 </h7> <br /> 
        <h7> CipherText 2 : @Model.encryptionResult.decrypted1 </h7><br />
        <h7> Final CipherText : @Model.encryptionResult.finaltext </h7>
    </div>
}
@if (!string.IsNullOrEmpty(Model.decryptionResult.decrypted1)
&& !string.IsNullOrEmpty(Model.decryptionResult.encrypted1) &&
!string.IsNullOrEmpty(Model.decryptionResult.finaltext))
{

    <br />
    <h5> Decryption(DED) Results </h5>
    <div>
        <h7> Final CipherText : @Model.EncryptedText </h7> <br/> 
        <h7> CipherText 2 : @Model.decryptionResult.decrypted1 </h7> <br />
        <h7> CipherText 1 : @Model.decryptionResult.encrypted1 </h7><br />
        <h7> Original Text : @Model.decryptionResult.finaltext </h7>
    </div>
}


@if (!string.IsNullOrEmpty(Model.DecryptedText))
{
    <br />
   
    <div>
        <h4>Decrypted Text:</h4>
        <p style="color:darkblue; background-color:lightgreen; width:fit-content"> @Model.DecryptedText</p>
       
    </div>
}
@*
@if (!ViewData.ModelState.IsValid)
{
    <div style="color: red;">
        @Html.ValidationSummary()
    </div>
} *@

SampleProject/Views/Encryption/Index.cshtml
@model EncryptionModel

@{
    ViewBag.Title = "3DES Encryption Example";
}

<h2>3DES Encryption Example</h2>

@using (Html.BeginForm("Encrypt", "Encryption", FormMethod.Post))
{
    <div>
        <label>Text to Encrypt:</label>
        @Html.TextBoxFor(m => m.TextToEncrypt)
    </div>
    <div>
        <label>Key (24 characters):</label>
        @Html.TextBoxFor(m => m.Key)
    </div>
    <div>
        <input type="submit" value="Encrypt" />
    </div>
}

@if (!string.IsNullOrEmpty(Model.EncryptedText))
{
    <div>
        <h4>Encrypted Text:</h4>
        <p>@Model.EncryptedText</p>
    </div>
}

@using (Html.BeginForm("Decrypt", "Encryption", FormMethod.Post))
{
    <div>
        <label>Encrypted Text:</label>
        @Html.TextBoxFor(m => m.EncryptedText)
    </div>
    <div>
        <label>Key (24 characters):</label>
        @Html.TextBoxFor(m => m.Key)
    </div>
    <div>
        <input type="submit" value="Decrypt" />
    </div>
}

@if (!string.IsNullOrEmpty(Model.DecryptedText))
{
    <div>
        <h4>Decrypted Text:</h4>
        <p>@Model.DecryptedText</p>
    </div>
}

@if (!ViewData.ModelState.IsValid)
{
    <div style="color: red;">
        @Html.ValidationSummary()
    </div>
}

SampleProject/Views/Encryption/RSAStatus.cshtml
 @model bool

@if(Model)
{
<div class="alert alert-success">
    <p>@TempData["success"]</p>
</div>
<h1> Success </h1>
}
@if(Model == false ) 
{
    <h7 style="color:red"> Error occured : Failed to perform the operation </h7>
}

<div>
    <br />
    <a href="@Url.Action("RSAEncryptDecryptIndex", "Encryption")">Back</a>
</div>

SampleProject/Views/Encryption/RSAencryptdecryptIndex.cshtml
@model RSAModel

<div>

@if (TempData["SubmitPublicKeyFromClientsuccess"] != null)
{
    <div class="alert alert-success">
        @TempData["SubmitPublicKeyFromClientsuccess"]
    </div>
}





<div style="position:center ; text-align:center">

    @using (Html.BeginForm("RsaEncrypt", "Encryption", FormMethod.Post))
    {
        <div>
            <h2> RSA Algorithm </h2>
            <input type="hidden" name="privateKey" value="@Model.privateKeygeneration" />
            <input type="hidden" name="publicKey" value="@Model.publicKeygeneration" />

            <label>Text to Encrypt:</label>
            <input type="text" name="model.RSAencryption.Text" placeholder="Enter Text" value="@Model.RSAencryption.Text" />
            @*   @Html.TextBoxFor(m => m.RSAencryption.Text) *@
        </div>
        <div>
            <label>Public Key:</label>
            <input type="text" name="model.RSAencryption.UserInputKey" placeholder="Enter Public Key" />
            @*   @Html.TextBoxFor(m => m.RSAencryption.PublicKey) *@
        </div>
        <div>
            <br />
            <input type="hidden" name="client" value="client1" />
            <input class="btn btn-primary" type="submit" value="Encrypt" />
            <input class="btn btn-info" type="submit" asp-controller="Encryption" asp-action="GenerateKeyforClient1" value="Generate Keys" />
        </div>
        <br />

    }

    @* digital signature  *@


    @using (Html.BeginForm("SignMessage", "Encryption", FormMethod.Post))

    {

        <h6> Create Signature </h6>
        <h7> Text </h7>  <input type="text" name="message" value="@Model.RSAencryption.Text" /> <br />
        <h7> Private Key</h7> <input type="text" name="privateKey" value="" /> <br />
        <input type="hidden" name="publicKey" value="@Model.RSAencryption.PublicKey" />
        @* <h7> Encrypted Text </h7>  *@
        <input type="hidden" name="hexString" value="@Model.RSAencryption.HexString" />

        <br />


        <input class="btn btn-primary" type="submit" value="Create" />


    }

    @using (Html.BeginForm("VerifySignature", "Encryption", FormMethod.Post))

    {

        <br />
        <div>
            <h6> Decrypt Text &  Verify Signature </h6>

            <h7> CipherText </h7> <textarea type="text" name="model.RSAencryption.HexString" value="@Model.RSAencryption.HexString" placeholder="Add CipherText" cols="50"> @Model.RSAencryption.HexString  </textarea> <br />
            <h7> Private Key </h7>  <input type="text" name="privateKey" placeholder="Enter private key to decrypt cipher"  size="30" /> <br /> <br />
            <h7> Signature </h7>  <textarea type="text" name="model.Signature" value="@Model.Signature" cols="50"> @Model.Signature </textarea>  <br />
            <h7> Public Key</h7> <input type="text" name="publicKey" value="" placeholder="Enter public key to verify signature" size="30" />  <br /> <br />
            <input type="hidden" name="model.RSAencryption.PublicKey" value="@Model.RSAencryption.PublicKey" />
            <input type="hidden" name="model.RSAencryption.PrivateKey" value="@Model.RSAencryption.PrivateKey" /> <br />

            @if( !string.IsNullOrEmpty(Model.HashOutput))
            {
             <h7> Hash </h7>   <input type="text" name="model.HashOutput" value="@Model.HashOutput" placeholder="Add Signature" /> <br />
            }
            @if (Model.DisplayDecryptedTextInTextBox)
            {
                <h7> Original Text </h7>  <input type="text" name="model.RSAdecryption.DecryptedText" value="@Model.RSAdecryption.DecryptedText" placeholder="Enter original text" /> <br /> <br />
            }
            <input class="btn btn-primary" type="submit" asp-controller="Encryption" asp-action="RsaDecrypt" value="Decrypt CipherText" />

            <input class="btn btn-primary" asp-controller="Encryption" asp-action="HashText" type="submit" value="Hash" />
            <input class="btn btn-primary" type="submit" value="Verify Signature" />

        </div>

    }

    @if (!string.IsNullOrWhiteSpace(Model.Signature) && Model.DisplaySignature)
    {
        <br />
        <h6> Signature(Hex) : @Model.Signature </h6>
    }



    </div>

    @* decrypt *@

    @*   @using (Html.BeginForm(FormMethod.Post))
    {

    <div style="text-align:center; height:initial">
    <div>

    <h4>Decrypt</h4>

    </div>


    <input type="hidden" name="client" value="client1" />


    <input type="hidden" name="OriginalText" value="@Model.RSAencryption.Text" />
    <H7> CipherText(Hex)</H7> @Html.TextBoxFor(m => m.RSAencryption.HexString, new { Name = "encryptedText" })<br />
    <h7> Private Key </h7>  <input type="text" name="key" placeholder="Enter key" /> <br /> <br />
    <input class="btn btn-primary" type="submit" asp-controller="Encryption" asp-action="RsaDecrypt" value="Decrypt" />
    <input class="btn btn-info" type="submit" asp-controller="Encryption" asp-action="GenerateKeyforClient1" value="Generate Keys" />
    </div>

    } *@
    </br>

    @if (Model.RSAdecryption != null)
    {
        if (!string.IsNullOrWhiteSpace(Model.RSAdecryption.DecryptedText))
        {
            <div style="text-align:left; height:auto">
                <h4> CipherText(Hex) </h4>
                <p style="color:darkblue; text-align:left;width:auto"> @Model.RSAdecryption.EncryptedText</p>
                <h4>Original Text</h4>
                <p style="color:darkblue; text-align:left;width:auto"> @Model.RSAdecryption.DecryptedText</p>

            </div>

        }
    }
</div>
<br />
<div>
    @if (!string.IsNullOrEmpty(Model.HashOutput))
    {
        <h6>  Hash : @Model.HashOutput </h6> <br/>
    }
</div>



<div>

    @if(Model.VerifiedSignature == RSAModel.VerifiedSign.YES)
    {
        <h6 style="color:purple"> Verified Signature : <h6 style="color:forestgreen">  Yes </h6> </h6>
    }else @if(Model.VerifiedSignature == RSAModel.VerifiedSign.NO)
    {
        <h6 style="color:purple"> Verified Signature :  <h6 style="color:red"> N0 </h6> </h6>
    } 
    else
    {
        <h6 style="color:purple"> Verified Signature :  <h6 style="color:red"> N/A </h6> </h6>
    }
    <br />
</div>


<div style="text-align:left">

    @if (!string.IsNullOrWhiteSpace(Model.RSAencryption?.HexString))
    {
        <h7> <h6><b> Encrypted </b> </h6>  @Model.RSAencryption.HexString </h7> <br /><br/>
    }
    @if (!string.IsNullOrEmpty(Model.RSAencryption.PrivateKey) && !string.IsNullOrEmpty(Model.RSAencryption.PublicKey))
    {
        <h7> <h6> <b> Public key </b>  </h6><textarea id="TextToCopy1" style="height:200px ; width:700px" readonly> @Model.RSAencryption.PublicKey </textarea> </h7>
        <button class="copyButton" onclick="copyTextToClipboard()" data-clipboard-target="#TextToCopy1"> &#x1f4cb; Copy </button> 
          <span id="copyMessage1" style="display:none; color:green; margin-left: 10px;">Text copied!</span> <br/> <br/>


        <h7> <h6> <b> Private key </b>  </h6> <textarea id="TextToCopy2" style="height:200px ; width:700px" readonly>  @Model.RSAencryption.PrivateKey </textarea> </h7>
          <button class="copyButton" onclick="copyTextToClipboard()" data-clipboard-target="#TextToCopy2"> &#x1f4cb; Copy </button>
            <span id="copyMessage2" style="display:none; color:green; margin-left: 10px;">Text copied!</span>

    }


</div>

<div style="text-align:left">


    @if (!string.IsNullOrEmpty(Model.publicKeygeneration) && !string.IsNullOrWhiteSpace(Model.privateKeygeneration))
    {

        <br />
        <h7> <h6><b> Public key </b> </h6><textarea id="TextToCopy1" style="height:200px ; width:700px" readonly> @Model.publicKeygeneration </textarea> </h7> 
          <button class="copyButton" onclick="copyTextToClipboard()" data-clipboard-target="#TextToCopy1"> &#x1f4cb; Copy </button> 
          <span id="copyMessage1" style="display:none; color:green; margin-left: 10px;">Text copied!</span> <br/> <br/>

        <h7><h6><b> Private Key </b> </h6> <textarea id="TextToCopy2" style="height:200px ; width:700px" readonly>  @Model.privateKeygeneration > </textarea>
            <button class="copyButton" onclick="copyTextToClipboard()" data-clipboard-target="#TextToCopy2"> &#x1f4cb; Copy </button>
            <span id="copyMessage2" style="display:none; color:green; margin-left: 10px;">Text copied!</span>

        </H7>
    }
</div>

<script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.8/dist/clipboard.min.js"></script>

<script>
    // Initialize Clipboard.js for all copy buttons
    var clipboard = new ClipboardJS('.copyButton');

    // Show message when the text is successfully copied
    clipboard.on('success', function(e) {
        // Show the "Text copied!" message for the relevant textarea
        var targetId = e.trigger.getAttribute('data-clipboard-target'); // Get the target textarea's ID
        var messageElement = document.getElementById("copyMessage" + targetId.charAt(targetId.length - 1)); // Get the corresponding message span
        messageElement.style.display = 'inline'; // Show the message

        // Hide the message after 2 seconds
        setTimeout(function() {
            messageElement.style.display = 'none';
        }, 2000);

        e.clearSelection(); // Clear the text selection
    });

    clipboard.on('error', function(e) {
        console.error("Error copying text.");
    });
</script>

SampleProject/Views/Encryption/SubmitKeys.cshtml
@model SubmitKeyModel

@{
    ViewBag.Title = "DES Encryption Example";
}

<h2> Submit Key?</h2>


@using (Html.BeginForm(FormMethod.Post))
{
 @*    <div>

        <label>Your Email:</label>
        @Html.TextBoxFor(m => m.OriginEmail, new { @class = "control-label col-md-2", placeholder = "Your Email" })
    </div>
    <div>
        <label>Password: </label>
        @Html.PasswordFor(m => m.EmailPassword, new { @class = "control-label col-md-2", placeholder = "Password" })
    </div>
    <div>
        <label>Source Email:</label>
        @Html.TextBoxFor(m => m.SourceEmail, new { @class = "control-label col-md-2", placeholder = "Source Email" })
    </div>


    <div>
        <br /> *@
        <br />
      <div>
        <input class="btn btn-primary" type="submit" asp-controller="Encryption" asp-action="RSAEncryptDecryptIndex" value="Back" />
        <input class="btn btn-default" type="submit" asp-controller="Encryption" asp-action="SubmitPublicKeyForClient1" value="Submit" />
    </div>
    <br />
}

SampleProject/Views/Encryption/SubmitKeysToClient2.cshtml
@model SubmitKeyModel

@{
    ViewBag.Title = "Submit Key";
}

<h2> Submit Key?</h2>


@using (Html.BeginForm(FormMethod.Post))
{
    @*    <div>

        <label>Your Email:</label>
        @Html.TextBoxFor(m => m.OriginEmail, new { @class = "control-label col-md-2", placeholder = "Your Email" })
    </div>
    <div>
        <label>Password: </label>
        @Html.PasswordFor(m => m.EmailPassword, new { @class = "control-label col-md-2", placeholder = "Password" })
    </div>
    <div>
        <label>Source Email:</label>
        @Html.TextBoxFor(m => m.SourceEmail, new { @class = "control-label col-md-2", placeholder = "Source Email" })
    </div>


    <div>
        <br /> *@
    <br />
    <div>
        <input class="btn btn-primary" type="submit" asp-controller="Encryption" asp-action="RSAEncryptDecryptIndex" value="Back" />
        <input class="btn btn-default" type="submit" asp-controller="Encryption" asp-action="SubmitPublicKeyForClient2" value="Submit" />
    </div>
    <br />
}