SampleProject/Controllers/UserProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SampleProject.DAL.Interface;
using SampleProject.Models;

namespace SampleProject.Controllers
{
    public class UserProductController : Controller
    {
        

        private readonly IUserProductRepository userProductRepository;
        public UserProductController(IUserProductRepository userProductRepository)
        {

            this.userProductRepository = userProductRepository;
        }



        public async Task<IActionResult> Index()
        {
            var userproductResponse = await userProductRepository.GetAll();
            return View(userproductResponse);

        }

        public async Task<IActionResult> Create()
        {
            var response = await userProductRepository.GetAllUserProductList();
            return View(response); 
        }



     
        //public async Task<IActionResult> AddOrder(int userId, int productId)
        //{
        //    //get user by id
        //    var user = await _userRepository.GetById(userId);

        //    if (user == null) { return NotFound(); }

        //     var product = await  _productRepository.GetById(productId);

        //      if(product == null) return NotFound();    


        //     var response=   await userProductRepository.PurchaseProduct(userId, productId);

        //    return View(response);

        //    //check if its valid 


        //    //add user to the product in userproduct table 


        //    //if (user == null)
        //    //{
        //    //    return NotFound();
        //    //}
        //   return View(user);
        //}
    }
}

SampleProject/Views/UserProduct/Create.cshtml
@model UserProductList

@{
    ViewBag.Title = "Create";
}

<h2>Create Orders</h2>

<br/>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

   
    <form  onsubmit="var sel=document.getElementById('product');document.getElementById('product_id').value=sel.options[sel.selectedIndex].text;">
            <div class="col-md-10">

          
                <select class="form-select" style="width:200px" name="Product" id="Product">
                <option value="0">
                    Select Product </option>
                    @foreach (var product in Model.Products)
                    {

                    <option value="@product.Id"> @product.Name</option>


                    } 
                    
                   
           
                   
          
        </select>
        
        <br/>
        <div >

                <select class="form-select" style="width:200px" name="User" id="User">
                    <option value="0">Select User</option>
                    @foreach (var user in Model.Users)
                    {
                        <option value="@user.Id"> @user.Name</option>

                    }
                </select>
      
        </div>
        <br/>
        <br />
        <input type="submit" name="submit" />
    </form>
   
    
}

SampleProject/Views/UserProduct/Index.cshtml
@model List<UserProductResponse>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Orders</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Users</th>

            <th>Product Purchased </th>



        </tr>
    </thead>
    <tbody>
        @foreach (var userProduct in Model)
        {
            <tr>

                <td>@userProduct.User.Name</td>
                <td>@userProduct.Product.Name</td>
               

                <td>
                    @*                   <a class="btn btn-primary" asp-controller="User" asp-action="UpdateUser" asp-route-userId="@user.Id
                ">Edit</a> *@

          @*           <a class="btn btn-primary" asp-controller="UserProduct" asp-action="ViewUserProduct" asp-route-userId="@user.Id
        ">View</a> *@
                    <a class="btn btn-primary" asp-controller="UserProduct" asp-action="Delete" asp-route-userproductId="@userProduct.Id

            ">Delete</a>
                </td>
            </tr>
        }
    </tbody>
    <a class="btn btn-primary" asp-controller="UserProduct" asp-action="Create">
        Add Order
    </a>
</table>